# Generated by Django 4.0.4 on 2022-06-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='DateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
