# Generated by Django 4.0.4 on 2022-06-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editapp', '0002_alter_userprofile_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Udate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
