# Generated by Django 4.0.4 on 2022-06-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editapp', '0003_alter_userprofile_udate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Cdate',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Udate',
            field=models.TimeField(auto_now=True),
        ),
    ]
