# Generated by Django 4.0.4 on 2022-06-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editapp', '0004_alter_userprofile_cdate_alter_userprofile_udate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Cdate',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Current',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Udate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
