# Generated by Django 4.0.4 on 2022-06-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editapp', '0005_remove_userprofile_cdate_userprofile_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Current',
        ),
    ]
