# Generated by Django 4.0.4 on 2022-06-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editapp', '0006_remove_userprofile_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Cdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
