# Generated by Django 4.0.4 on 2022-09-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editapp', '0007_userprofile_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(upload_to='media/profile'),
        ),
    ]
